name: CI

on: [push, pull_request]

jobs:
  repro:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ['windows', 'ubuntu', 'macos']
        ruby: [ ruby-head, '3.1', '3.0', '2.7', '2.6', '2.5' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Test
        run: bundle exec rake
